### ISSUE TITLE
Mechanic dashboard not scaling properly

### ISSUE THREAD

**Issue by Marvo5** [PatrykDu/popcorn-works-fastapi-fullstack-app#15]
Mechanic dashboard is not scaling properly.
![Zrzut ekranu 2024-03-18 180057](https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/assets/113666877/ee789faa-3874-4af4-84a4-91f264b3ee0f)

**Comment by PatrykDu** [comment]
![image](https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/assets/10407273/5d7f7ab5-68e0-40f3-9a64-73518dbbf940)
