### ISSUE TITLE
msg under table header

### ISSUE THREAD

**Issue by Marvo5** [PatrykDu/popcorn-works-fastapi-fullstack-app#18]
After adding new repair, should be redirected to mechanic/repairs.
Currently showing msg under table header
![Zrzut ekranu 2024-03-18 182420](https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/assets/113666877/7aca9969-fe0b-4a06-a457-ec96d5d5ddbc)

**Comment by PatrykDu** [comment]
Added redirection after adding new repair
