### ISSUE TITLE
Upgrade /mechanic/repairs/{repair_id}

### ISSUE THREAD

**Issue by PatrykDu** [PatrykDu/popcorn-works-fastapi-fullstack-app#22]
**Few things can be improved here:**

- ${\color{red}Filtering}$ ${\color{red}in}$ ${\color{red}add}$ ${\color{red}new }$ ${\color{red}parts }$ - right now we have to find parts in the drop down list, which can be hard when there are hundreds of items. You can copy filtering feature from /mechanic/storage endpoint.
- ${\color{blue}Amount }$ ${\color{blue}of }$ ${\color{blue}parts }$ ${\color{blue}in}$ ${\color{blue}repair }$ - there should be amount of the parts used in one repair, not Part.amount_left of all parts from the storage
- ${\color{green}Repair }$ ${\color{green}cost }$ - dynamic cost of all parts. When new part is added to the repair, Repair.money should be updated

There should be also option to remove added part from the repair or change amount of used parts.

![image](https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/assets/10407273/06066461-30e1-4b38-a0a7-6fd797dd6c63)

**Comment by PatrykDu** [comment]
Blue and green features added. Red is still not implemented

**Comment by Marvo5** [comment]
https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/pull/37

Filtering added, issue closed
