### ISSUE TITLE
Redirection of repair_id

### ISSUE THREAD

**Issue by Marvo5** [PatrykDu/popcorn-works-fastapi-fullstack-app#26]
Right now we can force enter repair id of diffrent customer.
Change it, so before fetching request his identity is checked.

**Comment by PatrykDu** [comment]
Added condition checking if endpoint reached by customer can be seen by him and added redirection if it cant be.
![image](https://github.com/PatrykDu/popcorn-works-fastapi-fullstack-app/assets/10407273/bd86d6af-1819-471f-bb56-55258cea3f81)
